apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
- argocd-ingress.yaml


configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
    - server.insecure=true